### ISSUE TITLE
Failed to fetch metrics

### ISSUE THREAD

**Issue by mfominov** [camptocamp/ipahealthcheck_exporter#1]
I've started systemd unit and on curl metrics endpoint i see empty reply.
In logs i see error.
Jun 01 17:19:05 pkles-gt0002399.novalocal ipahealthcheck_exporter[6377]: time="2021-06-01T17:19:05+03:00" level=info msg="ipa-healthcheck exporter listening on http://0.0.0.0:98>
Jun 01 17:21:35 pkles-gt0002399.novalocal ipahealthcheck_exporter[6377]: time="2021-06-01T17:21:35+03:00" level=info msg="Scraping metrics from /usr/bin/ipa-healthcheck" source=>
Jun 01 17:21:36 pkles-gt0002399.novalocal ipahealthcheck_exporter[6377]: time="2021-06-01T17:21:36+03:00" level=info msg="ipa-healthcheck tool returned errors: exit status 1" so>
Jun 01 17:21:36 pkles-gt0002399.novalocal ipahealthcheck_exporter[6377]: time="2021-06-01T17:21:36+03:00" level=fatal msg="Cannot unmarshal json from ipa-healthcheck output: une>
Jun 01 17:21:36 pkles-gt0002399.novalocal systemd[1]: ipahealthcheck_exporter.service: Main process exited, code=exited, status=1/FAILURE
Jun 01

**Comment by mfominov** [comment]
Command
/usr/bin/ipa-healthcheck returns json with exit code 1

**Comment by mfominov** [comment]
In our case we using docker container with freeipa.
User ipahealthcheck-exporter doesn't have keytab file.
If systemd service runs as user root there is no errors.

**Comment by lconsuegra** [comment]
Hello,

First your logs seems to be truncated, if you use the systemctl status command maybe add the -l options and pipe it to less.

About your issue it seems to be a permissions problem, what is the output if you launch the /usr/bin/ipa-healthcheck command as your non-root user ? 

For the ipahealthcheck_exporter to work as a user you need the ipa-healthcheck to work first when run as this user.


Regards.

**Comment by tgerczei** [comment]
You can now configure the exporter to use sudo, which will probably solve your problem.

**Comment by lconsuegra** [comment]
Hello @mfominov, 

Did you check if @tgerczei new feature solve your problem ?

Regards
