### ISSUE TITLE
Please add an option to set the listening IP address to localhost

### ISSUE THREAD

**Issue by dmgeurts** [camptocamp/ipahealthcheck_exporter#10]
Thank you for the exporter!

Trying to get all network traffic encrypted and store telemetry outside of the IPA server I'm looking at ingesting the Prometheus data using Telegraf where I can ship the data once a day to InfluxDB. The Telegraf agent is already present and securely ships system telemetry, so it's easy for me to just add another input there.

It would be great to have the option of not exposing the Prometheus port, when only needing a localhost connection.

**Comment by lconsuegra** [comment]
Hello, 

I have built a pre release with the requested change : [releases/v0.0.14-rc7](https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.14-rc7)

You can now launch the exporter like this : 
```
./ipahealthcheck_exporter -address localhost
INFO[0000] ipa-healthcheck exporter listening on http://localhost:9888  source="ipahealthcheck_exporter.go:238"
```

Can you test it please ? If its ok I will do a new release. Thanks.

**Comment by dmgeurts** [comment]
Hi, yes I can confirm this restricts the process to localhost:

```
user@ipa:~$ sudo /root/go/bin/ipahealthcheck_exporter -address localhost
INFO[0000] ipa-healthcheck exporter listening on http://localhost:9888  source="ipahealthcheck_exporter.go:238"
```

```
user@ipa:~$ sudo netstat -ltnp | grep 9888
tcp        0      0 127.0.0.1:9888          0.0.0.0:*               LISTEN      2338443/ipahealthch

```

**Comment by lconsuegra** [comment]
Added in the release [(https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.15] (v0.0.15)

Regards.
