### ISSUE TITLE
Services ipa_dnskeysyncd and named missing

### ISSUE THREAD

**Issue by kenytux** [camptocamp/ipahealthcheck_exporter#11]
Hello,
In the list of services (ipa_service_state) it is still missing "ipa_dnskeysyncd" and "named".
But if I look in "/var/log/ipa/healthcheck/healthcheck.log", these two services are there.

```
# HELP ipa_service_state State of the services monitored by IPA healthcheck (1: running, 0: not running)
# TYPE ipa_service_state gauge
ipa_service_state{service="certmonger"} 1
ipa_service_state{service="dirsrv"} 1
ipa_service_state{service="gssproxy"} 1
ipa_service_state{service="httpd"} 1
ipa_service_state{service="ipa_custodia"} 1
ipa_service_state{service="ipa_otpd"} 1
ipa_service_state{service="kadmin"} 1
ipa_service_state{service="krb5kdc"} 1
ipa_service_state{service="pki_tomcatd"} 1
ipa_service_state{service="sssd"} 1
```

```  
{
    "source": "ipahealthcheck.meta.services",
    "check": "ipa_dnskeysyncd",
    "result": "SUCCESS",
    "uuid": "02d729ef-e1a9-4f4b-b8ec-3636bab7f5e5",
    "when": "20230525210918Z",
    "duration": "0.027094",
    "kw": {
      "status": true
    }
  },
  {
    "source": "ipahealthcheck.meta.services",
    "check": "named",
    "result": "SUCCESS",
    "uuid": "e283ab08-faad-4f2c-a668-dfbe4fe48428",
    "when": "20230525210918Z",
    "duration": "0.026866",
    "kw": {
      "status": true
    }
  }
```

**Comment by kenytux** [comment]
It's happening only if I use "ipahealthcheck_exporter" as service!

**Comment by lconsuegra** [comment]
Hello,

The ipa services state are queried directly from the ipa-healthcheck command output (the logfile is parsed for the other checks) 

If you launch the following command does the _ipa_dnskeysyncd_ and _named_ checks are printed ? 
 
`ipa-healthcheck --source ipahealthcheck.meta.services --all`

**Comment by AleftinaT** [comment]
Hello! Same here.
Option --all shows named and ipa_dnskeysyncd
![image](https://github.com/camptocamp/ipahealthcheck_exporter/assets/81955571/94412077-7679-4b03-8e8a-5ed145f6e846)

**Comment by lconsuegra** [comment]
Hello,

Alright so can you install the [latest](https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.16-rc1) release to be sure its not a problem with the previous versions.

Then with this release can you : 

- Launch a new instance in verbose mode : 
`# ./ipahealthcheck_exporter -v -port 9999`

- Scrape the metrics :
`# curl localhost:9999/metrics`

- Paste the return of the exporter.


Thank you.

**Comment by lconsuegra** [comment]
I will close this issue since the exporter has evolved a lot since then. 
Please try the latest version an reopen if you still have the issue.

Regards.

**Comment by lconsuegra** [comment]
I will close this issue since the exporter has evolved a lot since then. 
Please try the latest version an reopen if you still have the issue.

Regards.
